// Public surface of the fleet contract module.
//
// Story 1.1 shipped one read-only command; 1.2 added the inventory and 1.3 the
// provenance core, its run context, and the MCP adapter. Later Epic 1 stories
// consume all of it from here rather than re-deriving authority, registry, or
// probe answers, which is the whole point of having a contract.

export {
  FLEET_CONTRACT_RELATIVE_PATH,
  collectFleetExtensions,
  loadFleetContract,
  resolveFleetContractPath,
  serializeFleetContract,
  validateFleetContract,
  type FleetContractValidation,
  type LoadedFleetContract,
} from "./contract";

export { fleetParserFailureEnvelope, inspectFleetContract, isFleetJsonInvocation, registerFleetCli } from "./cli";

export {
  buildAuthorityIndex,
  classifyPath,
  collectFleetInventory,
  conflictGroupId,
  detectConflicts,
  isSafePathSegment,
  matchException,
  readAgentRegistryRaw,
  readProjectRegistryRaw,
  resolveInventoryStores,
  resolveProfileLayout,
  type FleetAuthorityIndex,
  type FleetInventoryOptions,
  type ResolvedStore,
  type ResolvedStores,
} from "./inventory";

export {
  FLEET_DEFAULT_PROBE_TIMEOUT_MS,
  captureSelf,
  createRunContext,
  mapBounded,
  probe,
  probeEnv,
  remainingMs,
  throwIfCancelled,
  type FleetCaptureResult,
  type FleetProbeResult,
  type FleetRunContext,
  type FleetRunContextOptions,
} from "./runtime";

export {
  classifyExecutableFamily,
  collectFleetProvenance,
  compareFact,
  readConfiguredPin,
  resolveProvenanceSources,
  type ConfiguredPin,
  type FleetProvenanceOptions,
} from "./provenance";

export {
  auditChildEnv,
  auditRepository,
  collectFleetStatus,
  observeFromInventory,
  observeFromProvenance,
  resolveAuditCli,
  resolveStatusScope,
  rollUp,
  type AuditObservationResult,
  type FleetStatusContext,
  type FleetStatusOptions,
  type ResolvedStatusScope,
} from "./status";

export { registerFleetMcpTools } from "./mcp";

export {
  FLEET_COMMANDS,
  bounded,
  boundedContext,
  boundedNotes,
  boundedValue,
  cappedStrings,
  ignoreBrokenPipe,
  diagnosticDetails,
  fleetEnvelopeExitCode,
  fleetFailureEnvelope,
  fleetSuccessEnvelope,
  formatFleetContractReport,
  formatFleetErrorReport,
  formatFleetInventoryReport,
  formatFleetProvenanceReport,
  formatFleetStatusReport,
  normalizeFleetError,
  redactHome,
  renderFleetJson,
  validateFleetEnvelope,
  type BoundedContext,
  type FleetAuthorityView,
  type FleetClassificationView,
  type FleetContractInspection,
  type FleetEnvelopeV1,
  type FleetProjectionView,
  type FleetRetiredView,
} from "./output";

export {
  FLEET_ACTIVATION_STATES,
  FLEET_CLASSIFICATION_IDS,
  FLEET_CLASSIFICATION_REQUIRED_FIELDS,
  FLEET_FIELD_STATES,
  FLEET_FINDING_SEVERITIES,
  FLEET_HEALTHY_CLASSIFICATIONS,
  FLEET_HEALTHY_SECTIONS,
  FLEET_CONTRACT_SCHEMA_VERSION,
  FLEET_ERROR_CODES,
  FLEET_INVENTORY_MAX_ROWS,
  FLEET_PATH_CLASSIFICATIONS,
  FLEET_PROBE_OUTCOMES,
  FLEET_PROVENANCE_MAX_FACTS,
  FLEET_PROVENANCE_MAX_PROBES,
  FLEET_PROVENANCE_SIDE_STATES,
  FLEET_PROVENANCE_STATUSES,
  FLEET_PROVENANCE_STATUS_PRECEDENCE,
  FLEET_RETIRED_IDS,
  FLEET_STATUS_AUDIT_CONCURRENCY,
  FLEET_STATUS_DOMAINS,
  FLEET_STATUS_MAX_AGENTS,
  FLEET_STATUS_MAX_DETAILS,
  FLEET_STATUS_MAX_FINDINGS,
  FLEET_STATUS_MAX_OBSERVATIONS_PER_AGENT,
  FLEET_STATUS_STATE_PRECEDENCE,
  FLEET_STATUS_STATES,
  FLEET_SCHEMA_VERSION,
  FLEET_SUPPORTED_SCHEMA_VERSIONS,
  FleetError,
  fleetExitCode,
  type FleetActivation,
  type FleetAuthority,
  type FleetBoardBinding,
  type FleetClassification,
  type FleetConflictGroup,
  type FleetContract,
  type FleetDiagnostic,
  type FleetErrorCode,
  type FleetExtension,
  type FleetFieldState,
  type FleetFieldValue,
  type FleetFindingSeverity,
  type FleetInventory,
  type FleetInventoryFinding,
  type FleetInventoryHealth,
  type FleetInventoryRow,
  type FleetInventoryScope,
  type FleetInventoryTotals,
  type FleetManifestEvidence,
  type FleetPathClassification,
  type FleetPathView,
  type FleetProbeOutcome,
  type FleetProbeRecord,
  type FleetProjection,
  type FleetProvenance,
  type FleetProvenanceFact,
  type FleetProvenanceHealth,
  type FleetProvenanceSide,
  type FleetProvenanceSideState,
  type FleetProvenanceSourceView,
  type FleetProvenanceStatus,
  type FleetProvenanceTotals,
  type FleetRetiredMode,
  type FleetServiceModel,
  type FleetStatus,
  type FleetStatusAgent,
  type FleetStatusDomain,
  type FleetStatusDomainRollup,
  type FleetStatusHealth,
  type FleetStatusHostFinding,
  type FleetStatusObservation,
  type FleetStatusScope,
  type FleetStatusState,
  type FleetStatusTotals,
  type FleetStoreView,
} from "./types";
