// Public surface of the fleet contract module.
//
// Story 1.1 shipped one read-only command; 1.2 added the inventory and 1.3 the
// provenance core, its run context, and the MCP adapter. Later Epic 1 stories
// consume all of it from here rather than re-deriving authority, registry, or
// probe answers, which is the whole point of having a contract.

export {
  FLEET_CONTRACT_RELATIVE_PATH,
  collectFleetExtensions,
  loadFleetContract,
  resolveFleetContractPath,
  serializeFleetContract,
  validateFleetContract,
  type FleetContractValidation,
  type LoadedFleetContract,
} from "./contract";

export { fleetParserFailureEnvelope, inspectFleetContract, isFleetJsonInvocation, registerFleetCli } from "./cli";

export {
  buildAuthorityIndex,
  classifyPath,
  collectFleetInventory,
  conflictGroupId,
  declaredRowClass,
  detectConflicts,
  isSafePathSegment,
  matchException,
  readAgentRegistryRaw,
  readProjectRegistryRaw,
  resolveInventoryStores,
  resolveProfileLayout,
  type FleetAuthorityIndex,
  type FleetInventoryOptions,
  type ResolvedStore,
  type ResolvedStores,
} from "./inventory";

export {
  FLEET_DEFAULT_PROBE_TIMEOUT_MS,
  captureSelf,
  createRunContext,
  mapBounded,
  probe,
  probeEnv,
  probeRaw,
  probeText,
  remainingMs,
  throwIfCancelled,
  type FleetCaptureResult,
  type FleetProbeResult,
  type FleetProbeTextOptions,
  type FleetProbeTextResult,
  type FleetRawProbeResult,
  type FleetRunContext,
  type FleetRunContextOptions,
} from "./runtime";

export {
  classifyExecutableFamily,
  collectFleetProvenance,
  compareFact,
  readConfiguredPin,
  resolveProvenanceSources,
  type ConfiguredPin,
  type FleetProvenanceOptions,
} from "./provenance";

export {
  baselineScopeOf,
  boundTransitions,
  classifyMember,
  classifyObservation,
  compareStatusFindings,
  deriveSeverity,
  detectContradictions,
  diffFindings,
  emptyMembers,
  evaluateDomainFreshness,
  evaluateFleetHealth,
  evaluateFreshness,
  hostSortKey,
  needsJustification,
  observationGates,
  observationSortKey,
  parseBaselineDocument,
  readHealthPolicy,
  resolveJustification,
  snapshotCurrent,
  snapshotStatusDocument,
  type FleetHealthClassification,
  type FleetHealthInput,
  type FleetHealthObservationInput,
  type FleetHealthPolicyView,
  type FleetStatusBaseline,
  type FleetStatusBaselineScope,
  type FleetStatusContradiction,
  type FleetStatusFindingSnapshot,
  type FleetStatusSortable,
} from "./health";

export {
  SCAFFOLD_LINEAGE_DEPTH,
  SCAFFOLD_MAX_ASSET_BYTES,
  SCAFFOLD_MAX_ROLE_ENTRIES,
  SCAFFOLD_PROBE_KIND,
  collectScaffoldParity,
  type FleetScaffoldAgentInput,
  type FleetScaffoldAgentResult,
  type FleetScaffoldContext,
  type FleetScaffoldGroupResult,
  type FleetScaffoldParity,
  type FleetScaffoldSourceRecord,
} from "./scaffold";

export {
  PROFILE_MARKER_WINDOW_BYTES,
  PROFILE_MAX_DRIFT_SECTIONS,
  PROFILE_MAX_UNIT_FILE_BYTES,
  PROFILE_NAME_PATTERN,
  PROFILE_PROBE_KIND,
  PROFILE_PYTHON_PROBE,
  PROFILE_SINGLETON_LINKS,
  collectProfileHealth,
  type FleetProfileAgentInput,
  type FleetProfileAgentResult,
  type FleetProfileAspect,
  type FleetProfileContext,
  type FleetProfileExtras,
  type FleetProfileHealth,
  type FleetProfileItem,
  type FleetProfileRendererRecord,
  type FleetProfileRootRecord,
} from "./profile";

export {
  FLEET_STATUS_AUDIT_TIMEOUT_MS,
  agentLifecycle,
  auditChildEnv,
  auditRepository,
  collectFleetStatus,
  observeFromInventory,
  observeFromProvenance,
  resolveAuditCli,
  resolveStatusScope,
  rollUp,
  type AuditObservationResult,
  type FleetStatusContext,
  type FleetStatusOptions,
  type ResolvedStatusScope,
} from "./status";

export { registerFleetMcpTools } from "./mcp";

export {
  FLEET_COMMANDS,
  bounded,
  boundedContext,
  boundedNotes,
  boundedValue,
  cappedStrings,
  ignoreBrokenPipe,
  diagnosticDetails,
  fleetEnvelopeExitCode,
  fleetFailureEnvelope,
  fleetSuccessEnvelope,
  formatFleetContractReport,
  formatFleetErrorReport,
  formatFleetInventoryReport,
  formatFleetProvenanceReport,
  formatFleetStatusReport,
  normalizeFleetError,
  redactHome,
  renderFleetJson,
  validateFleetEnvelope,
  type BoundedContext,
  type FleetAuthorityView,
  type FleetClassificationView,
  type FleetContractInspection,
  type FleetEnvelopeV1,
  type FleetProjectionView,
  type FleetRetiredView,
} from "./output";

export {
  FLEET_ACTIVATION_STATES,
  FLEET_CLASSIFICATION_IDS,
  FLEET_CONTRACT_OPTIONAL_ROOT_KEYS,
  FLEET_CONTRACT_ROOT_KEYS,
  FLEET_HEALTH_POLICY_AGENT_EXCEPTION_KEYS,
  FLEET_HEALTH_POLICY_DEFERRED_KEYS,
  FLEET_HEALTH_POLICY_FRESHNESS_KEYS,
  FLEET_HEALTH_POLICY_KEYS,
  FLEET_HEALTH_POLICY_SKIP_KEYS,
  FLEET_HEALTH_POLICY_WARNING_KEYS,
  FLEET_CLASSIFICATION_REQUIRED_FIELDS,
  FLEET_FIELD_STATES,
  FLEET_FINDING_SEVERITIES,
  FLEET_HEALTHY_CLASSIFICATIONS,
  FLEET_HEALTHY_SECTIONS,
  FLEET_CONTRACT_SCHEMA_VERSION,
  FLEET_ERROR_CODES,
  FLEET_INVENTORY_MAX_ROWS,
  FLEET_PATH_CLASSIFICATIONS,
  FLEET_PROBE_OUTCOMES,
  FLEET_PROFILE_EXTRA_CLASSES,
  FLEET_PROFILE_EXTRA_GUIDANCE,
  FLEET_PROFILE_ITEM_KINDS,
  FLEET_PROFILE_MANIFEST_EXTRAS_KEYS,
  FLEET_PROFILE_MANIFEST_IDENTITY_KEYS,
  FLEET_PROFILE_MANIFEST_KEYS,
  FLEET_PROFILE_MANIFEST_LIMITS_KEYS,
  FLEET_PROFILE_MANIFEST_MEMORY_KEYS,
  FLEET_PROFILE_MANIFEST_RENDERER_KEYS,
  FLEET_PROFILE_MANIFEST_SKILL_CORE_KEYS,
  FLEET_PROFILE_PATH_CODES,
  FLEET_PROFILE_RENDERER_CODES,
  FLEET_PROFILE_RENDERER_STATES,
  FLEET_STATUS_PROFILE_CONCURRENCY,
  PROFILE_MAX_EXTRA_SKILLS,
  PROFILE_MAX_FILE_BYTES,
  PROFILE_MAX_ROOT_ENTRIES,
  PROFILE_MAX_UNIT_FILES,
  FLEET_PROVENANCE_MAX_FACTS,
  FLEET_PROVENANCE_MAX_PROBES,
  FLEET_PROVENANCE_SIDE_STATES,
  FLEET_PROVENANCE_STATUSES,
  FLEET_PROVENANCE_STATUS_PRECEDENCE,
  FLEET_RETIRED_IDS,
  FLEET_SCAFFOLD_ITEM_KINDS,
  FLEET_SCAFFOLD_MANIFEST_KEYS,
  FLEET_SCAFFOLD_PRESENCE_ONLY_KEYS,
  FLEET_SCAFFOLD_SOURCE_CODES,
  FLEET_STATUS_APPLICABILITIES,
  FLEET_STATUS_AUDIT_CONCURRENCY,
  FLEET_STATUS_DOMAINS,
  FLEET_STATUS_EVIDENCE,
  FLEET_STATUS_EXIT_CATEGORIES,
  FLEET_STATUS_EXIT_CODES,
  FLEET_STATUS_FRESHNESS,
  FLEET_STATUS_FRESHNESS_PRECEDENCE,
  FLEET_STATUS_JUSTIFICATION_KINDS,
  FLEET_STATUS_LIFECYCLE_STATES,
  FLEET_STATUS_READINESS,
  FLEET_STATUS_SCOPES,
  FLEET_STATUS_SCOPE_PRECEDENCE,
  FLEET_STATUS_MAX_AGENTS,
  FLEET_STATUS_MAX_DETAILS,
  FLEET_STATUS_MAX_FINDINGS,
  FLEET_STATUS_MAX_ITEMS,
  FLEET_STATUS_MAX_OBSERVATIONS_PER_AGENT,
  FLEET_STATUS_MAX_TRANSITIONS,
  FLEET_STATUS_MAX_WIP_OVERLAP,
  FLEET_STATUS_SCAFFOLD_CONCURRENCY,
  FLEET_STATUS_MEMBER_CLASSES,
  FLEET_STATUS_MEMBER_PRECEDENCE,
  FLEET_STATUS_NEXT_ACTION_CLASSES,
  FLEET_STATUS_REPAIRS,
  FLEET_STATUS_SEVERITIES,
  FLEET_STATUS_SEVERITY_PRECEDENCE,
  FLEET_STATUS_STATE_PRECEDENCE,
  FLEET_STATUS_STATES,
  FLEET_STATUS_TRANSITION_KINDS,
  FLEET_STATUS_VERDICTS,
  FLEET_SCHEMA_VERSION,
  FLEET_SUPPORTED_SCHEMA_VERSIONS,
  FleetError,
  fleetExitCode,
  type FleetActivation,
  type FleetActivationState,
  type FleetAuthority,
  type FleetBoardBinding,
  type FleetClassification,
  type FleetClassificationId,
  type FleetConflictGroup,
  type FleetContract,
  type FleetDiagnostic,
  type FleetErrorCode,
  type FleetExtension,
  type FleetFieldState,
  type FleetFieldValue,
  type FleetFindingSeverity,
  type FleetHealthPolicy,
  type FleetHealthPolicyAgentException,
  type FleetHealthPolicyAllowedSkip,
  type FleetHealthPolicyAllowedWarning,
  type FleetHealthPolicyDeferredCapability,
  type FleetHealthPolicyFreshness,
  type FleetInventory,
  type FleetInventoryFinding,
  type FleetInventoryHealth,
  type FleetInventoryRow,
  type FleetInventoryScope,
  type FleetInventoryTotals,
  type FleetManifestEvidence,
  type FleetPathClassification,
  type FleetPathView,
  type FleetProbeOutcome,
  type FleetProbeRecord,
  type FleetProfileExtraClass,
  type FleetProfileExtraGuidance,
  type FleetProfileItemKind,
  type FleetProfileManifest,
  type FleetProfilePathCode,
  type FleetProfileRendererCode,
  type FleetProfileRendererState,
  type FleetProfileSummary,
  type FleetProjection,
  type FleetProvenance,
  type FleetProvenanceFact,
  type FleetProvenanceHealth,
  type FleetProvenanceSide,
  type FleetProvenanceSideState,
  type FleetProvenanceSourceView,
  type FleetProvenanceStatus,
  type FleetProvenanceTotals,
  type FleetRetiredMode,
  type FleetScaffoldItemKind,
  type FleetScaffoldManifest,
  type FleetScaffoldPresenceOnly,
  type FleetScaffoldSourceCode,
  type FleetScaffoldSummary,
  type FleetServiceModel,
  type FleetStatus,
  type FleetStatusAgent,
  type FleetStatusAgentProfile,
  type FleetStatusAgentScaffold,
  type FleetStatusApplicability,
  type FleetStatusDomain,
  type FleetStatusDomainRollup,
  type FleetStatusEvidence,
  type FleetStatusExitCategory,
  type FleetStatusFinding,
  type FleetStatusFreshness,
  type FleetStatusHealth,
  type FleetStatusHostFinding,
  type FleetStatusJustification,
  type FleetStatusJustificationKind,
  type FleetStatusLifecycle,
  type FleetStatusLifecycleState,
  type FleetStatusMemberClass,
  type FleetStatusMembers,
  type FleetStatusNextActionClass,
  type FleetStatusObservation,
  type FleetStatusObservationItem,
  type FleetStatusProfileExtraItem,
  type FleetStatusReadiness,
  type FleetStatusRepair,
  type FleetStatusScope,
  type FleetStatusScopeKind,
  type FleetStatusSeverity,
  type FleetStatusState,
  type FleetStatusTotals,
  type FleetStatusTransition,
  type FleetStatusTransitionKind,
  type FleetStatusVerdict,
  type FleetStoreView,
} from "./types";
